Search.appendIndex(
    [
                {
            "fqsen": "\\LightnCandy\\Compiler",
            "name": "Compiler",
            "summary": "LightnCandy\u0020Compiler",
            "url": "classes/LightnCandy-Compiler.html"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcompileTemplate\u0028\u0029",
            "name": "compileTemplate",
            "summary": "Compile\u0020template\u0020into\u0020PHP\u0020code",
            "url": "classes/LightnCandy-Compiler.html#method_compileTemplate"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcomposePHPRender\u0028\u0029",
            "name": "composePHPRender",
            "summary": "Compose\u0020LightnCandy\u0020render\u0020codes\u0020for\u0020include\u0028\u0029",
            "url": "classes/LightnCandy-Compiler.html#method_composePHPRender"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AgetFuncName\u0028\u0029",
            "name": "getFuncName",
            "summary": "Get\u0020function\u0020name\u0020for\u0020standalone\u0020or\u0020none\u0020standalone\u0020template.",
            "url": "classes/LightnCandy-Compiler.html#method_getFuncName"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AgetVariableNames\u0028\u0029",
            "name": "getVariableNames",
            "summary": "Get\u0020string\u0020presentation\u0020of\u0020variables",
            "url": "classes/LightnCandy-Compiler.html#method_getVariableNames"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcompileSubExpression\u0028\u0029",
            "name": "compileSubExpression",
            "summary": "Get\u0020string\u0020presentation\u0020of\u0020a\u0020sub\u0020expression",
            "url": "classes/LightnCandy-Compiler.html#method_compileSubExpression"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AgetVariableNameOrSubExpression\u0028\u0029",
            "name": "getVariableNameOrSubExpression",
            "summary": "Get\u0020string\u0020presentation\u0020of\u0020a\u0020subexpression\u0020or\u0020a\u0020variable",
            "url": "classes/LightnCandy-Compiler.html#method_getVariableNameOrSubExpression"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AgetVariableName\u0028\u0029",
            "name": "getVariableName",
            "summary": "Get\u0020string\u0020presentation\u0020of\u0020a\u0020variable",
            "url": "classes/LightnCandy-Compiler.html#method_getVariableName"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcompileToken\u0028\u0029",
            "name": "compileToken",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_compileToken"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003Apartial\u0028\u0029",
            "name": "partial",
            "summary": "handle\u0020partial",
            "url": "classes/LightnCandy-Compiler.html#method_partial"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003Ainline\u0028\u0029",
            "name": "inline",
            "summary": "handle\u0020inline\u0020partial",
            "url": "classes/LightnCandy-Compiler.html#method_inline"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AinvertedSection\u0028\u0029",
            "name": "invertedSection",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020inverted\u0020section\u0020begin\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_invertedSection"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AblockCustomHelper\u0028\u0029",
            "name": "blockCustomHelper",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020block\u0020custom\u0020helper\u0020begin\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_blockCustomHelper"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AblockEnd\u0028\u0029",
            "name": "blockEnd",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020block\u0020end\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_blockEnd"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AblockBegin\u0028\u0029",
            "name": "blockBegin",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020block\u0020begin\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_blockBegin"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003Asection\u0028\u0029",
            "name": "section",
            "summary": "compile\u0020\u007B\u007B\u0023foo\u007D\u007D\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_section"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003Awith\u0028\u0029",
            "name": "with",
            "summary": "compile\u0020\u007B\u007Bwith\u007D\u007D\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_with"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcustomHelper\u0028\u0029",
            "name": "customHelper",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020custom\u0020helper\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_customHelper"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AdoElse\u0028\u0029",
            "name": "doElse",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020else\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_doElse"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcompileLog\u0028\u0029",
            "name": "compileLog",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020log\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_compileLog"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcompileLookup\u0028\u0029",
            "name": "compileLookup",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020lookup\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_compileLookup"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcompileOutput\u0028\u0029",
            "name": "compileOutput",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020template\u0020output",
            "url": "classes/LightnCandy-Compiler.html#method_compileOutput"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AcompileVariable\u0028\u0029",
            "name": "compileVariable",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020variable\u0020token",
            "url": "classes/LightnCandy-Compiler.html#method_compileVariable"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003AaddUsageCount\u0028\u0029",
            "name": "addUsageCount",
            "summary": "Add\u0020usage\u0020count\u0020to\u0020context",
            "url": "classes/LightnCandy-Compiler.html#method_addUsageCount"
        },                {
            "fqsen": "\\LightnCandy\\Compiler\u003A\u003A\u0024lastParsed",
            "name": "lastParsed",
            "summary": "",
            "url": "classes/LightnCandy-Compiler.html#property_lastParsed"
        },                {
            "fqsen": "\\LightnCandy\\Context",
            "name": "Context",
            "summary": "LightnCandy\u0020class\u0020to\u0020handle\u0020Context",
            "url": "classes/LightnCandy-Context.html"
        },                {
            "fqsen": "\\LightnCandy\\Context\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020context\u0020from\u0020options",
            "url": "classes/LightnCandy-Context.html#method_create"
        },                {
            "fqsen": "\\LightnCandy\\Context\u003A\u003AupdateHelperTable\u0028\u0029",
            "name": "updateHelperTable",
            "summary": "update\u0020specific\u0020custom\u0020helper\u0020table\u0020from\u0020options",
            "url": "classes/LightnCandy-Context.html#method_updateHelperTable"
        },                {
            "fqsen": "\\LightnCandy\\Context\u003A\u003Amerge\u0028\u0029",
            "name": "merge",
            "summary": "Merge\u0020a\u0020context\u0020into\u0020another",
            "url": "classes/LightnCandy-Context.html#method_merge"
        },                {
            "fqsen": "\\LightnCandy\\Encoder",
            "name": "Encoder",
            "summary": "LightnCandy\u0020class\u0020to\u0020encode.",
            "url": "classes/LightnCandy-Encoder.html"
        },                {
            "fqsen": "\\LightnCandy\\Encoder\u003A\u003Araw\u0028\u0029",
            "name": "raw",
            "summary": "Get\u0020string\u0020value",
            "url": "classes/LightnCandy-Encoder.html#method_raw"
        },                {
            "fqsen": "\\LightnCandy\\Encoder\u003A\u003Aenc\u0028\u0029",
            "name": "enc",
            "summary": "Get\u0020html\u0020encoded\u0020string",
            "url": "classes/LightnCandy-Encoder.html#method_enc"
        },                {
            "fqsen": "\\LightnCandy\\Encoder\u003A\u003Aencq\u0028\u0029",
            "name": "encq",
            "summary": "LightnCandy\u0020runtime\u0020method\u0020for\u0020\u007B\u007Bvar\u007D\u007D\u0020,\u0020and\u0020deal\u0020with\u0020single\u0020quote\u0020to\u0020same\u0020as\u0020handlebars.js\u0020.",
            "url": "classes/LightnCandy-Encoder.html#method_encq"
        },                {
            "fqsen": "\\LightnCandy\\Exporter",
            "name": "Exporter",
            "summary": "LightnCandy\u0020major\u0020static\u0020class",
            "url": "classes/LightnCandy-Exporter.html"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "Get\u0020PHP\u0020code\u0020string\u0020from\u0020a\u0020closure\u0020of\u0020function\u0020as\u0020string",
            "url": "classes/LightnCandy-Exporter.html#method_closure"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003Ahelpers\u0028\u0029",
            "name": "helpers",
            "summary": "Export\u0020required\u0020custom\u0020helper\u0020functions",
            "url": "classes/LightnCandy-Exporter.html#method_helpers"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003AreplaceSafeString\u0028\u0029",
            "name": "replaceSafeString",
            "summary": "Replace\u0020SafeString\u0020class\u0020with\u0020alias\u0020class\u0020name",
            "url": "classes/LightnCandy-Exporter.html#method_replaceSafeString"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003AgetClassMethods\u0028\u0029",
            "name": "getClassMethods",
            "summary": "Get\u0020methods\u0020from\u0020ReflectionClass",
            "url": "classes/LightnCandy-Exporter.html#method_getClassMethods"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003AgetClassStatics\u0028\u0029",
            "name": "getClassStatics",
            "summary": "Get\u0020statics\u0020code\u0020from\u0020ReflectionClass",
            "url": "classes/LightnCandy-Exporter.html#method_getClassStatics"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003AgetMeta\u0028\u0029",
            "name": "getMeta",
            "summary": "Get\u0020metadata\u0020from\u0020ReflectionObject",
            "url": "classes/LightnCandy-Exporter.html#method_getMeta"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003Asafestring\u0028\u0029",
            "name": "safestring",
            "summary": "Export\u0020SafeString\u0020class\u0020as\u0020string",
            "url": "classes/LightnCandy-Exporter.html#method_safestring"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003Astringobject\u0028\u0029",
            "name": "stringobject",
            "summary": "Export\u0020StringObject\u0020class\u0020as\u0020string",
            "url": "classes/LightnCandy-Exporter.html#method_stringobject"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003Aruntime\u0028\u0029",
            "name": "runtime",
            "summary": "Export\u0020required\u0020standalone\u0020Runtime\u0020methods",
            "url": "classes/LightnCandy-Exporter.html#method_runtime"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003Aconstants\u0028\u0029",
            "name": "constants",
            "summary": "Export\u0020Runtime\u0020constants",
            "url": "classes/LightnCandy-Exporter.html#method_constants"
        },                {
            "fqsen": "\\LightnCandy\\Exporter\u003A\u003AscanDependency\u0028\u0029",
            "name": "scanDependency",
            "summary": "Scan\u0020for\u0020required\u0020standalone\u0020functions",
            "url": "classes/LightnCandy-Exporter.html#method_scanDependency"
        },                {
            "fqsen": "\\LightnCandy\\Expression",
            "name": "Expression",
            "summary": "LightnCandy\u0020Expression\u0020handler",
            "url": "classes/LightnCandy-Expression.html"
        },                {
            "fqsen": "\\LightnCandy\\Expression\u003A\u003AboolString\u0028\u0029",
            "name": "boolString",
            "summary": "return\u0020\u0027true\u0027\u0020or\u0020\u0027false\u0027\u0020string.",
            "url": "classes/LightnCandy-Expression.html#method_boolString"
        },                {
            "fqsen": "\\LightnCandy\\Expression\u003A\u003AlistString\u0028\u0029",
            "name": "listString",
            "summary": "Get\u0020string\u0020presentation\u0020for\u0020a\u0020string\u0020list",
            "url": "classes/LightnCandy-Expression.html#method_listString"
        },                {
            "fqsen": "\\LightnCandy\\Expression\u003A\u003AarrayString\u0028\u0029",
            "name": "arrayString",
            "summary": "Get\u0020string\u0020presentation\u0020for\u0020an\u0020array",
            "url": "classes/LightnCandy-Expression.html#method_arrayString"
        },                {
            "fqsen": "\\LightnCandy\\Expression\u003A\u003Aanalyze\u0028\u0029",
            "name": "analyze",
            "summary": "Analyze\u0020an\u0020expression",
            "url": "classes/LightnCandy-Expression.html#method_analyze"
        },                {
            "fqsen": "\\LightnCandy\\Expression\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "get\u0020normalized\u0020handlebars\u0020expression\u0020for\u0020a\u0020variable",
            "url": "classes/LightnCandy-Expression.html#method_toString"
        },                {
            "fqsen": "\\LightnCandy\\Flags",
            "name": "Flags",
            "summary": "LightnCandy\u0020class\u0020to\u0020keep\u0020flag\u0020consts",
            "url": "classes/LightnCandy-Flags.html"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_ERROR_LOG",
            "name": "FLAG_ERROR_LOG",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_ERROR_LOG"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_ERROR_EXCEPTION",
            "name": "FLAG_ERROR_EXCEPTION",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_ERROR_EXCEPTION"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_JSTRUE",
            "name": "FLAG_JSTRUE",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_JSTRUE"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_JSOBJECT",
            "name": "FLAG_JSOBJECT",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_JSOBJECT"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_JSLENGTH",
            "name": "FLAG_JSLENGTH",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_JSLENGTH"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_THIS",
            "name": "FLAG_THIS",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_THIS"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_PARENT",
            "name": "FLAG_PARENT",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_PARENT"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_HBESCAPE",
            "name": "FLAG_HBESCAPE",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_HBESCAPE"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_ADVARNAME",
            "name": "FLAG_ADVARNAME",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_ADVARNAME"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_NAMEDARG",
            "name": "FLAG_NAMEDARG",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_NAMEDARG"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_SPVARS",
            "name": "FLAG_SPVARS",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_SPVARS"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_PREVENTINDENT",
            "name": "FLAG_PREVENTINDENT",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_PREVENTINDENT"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_SLASH",
            "name": "FLAG_SLASH",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_SLASH"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_ELSE",
            "name": "FLAG_ELSE",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_ELSE"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_RAWBLOCK",
            "name": "FLAG_RAWBLOCK",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_RAWBLOCK"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_HANDLEBARSLAMBDA",
            "name": "FLAG_HANDLEBARSLAMBDA",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_HANDLEBARSLAMBDA"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_PARTIALNEWCONTEXT",
            "name": "FLAG_PARTIALNEWCONTEXT",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_PARTIALNEWCONTEXT"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_IGNORESTANDALONE",
            "name": "FLAG_IGNORESTANDALONE",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_IGNORESTANDALONE"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_STRINGPARAMS",
            "name": "FLAG_STRINGPARAMS",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_STRINGPARAMS"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_KNOWNHELPERSONLY",
            "name": "FLAG_KNOWNHELPERSONLY",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_KNOWNHELPERSONLY"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_STANDALONEPHP",
            "name": "FLAG_STANDALONEPHP",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_STANDALONEPHP"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_EXTHELPER",
            "name": "FLAG_EXTHELPER",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_EXTHELPER"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_ECHO",
            "name": "FLAG_ECHO",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_ECHO"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_PROPERTY",
            "name": "FLAG_PROPERTY",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_PROPERTY"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_METHOD",
            "name": "FLAG_METHOD",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_METHOD"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_RUNTIMEPARTIAL",
            "name": "FLAG_RUNTIMEPARTIAL",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_RUNTIMEPARTIAL"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_NOESCAPE",
            "name": "FLAG_NOESCAPE",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_NOESCAPE"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_MUSTACHELOOKUP",
            "name": "FLAG_MUSTACHELOOKUP",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_MUSTACHELOOKUP"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_ERROR_SKIPPARTIAL",
            "name": "FLAG_ERROR_SKIPPARTIAL",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_ERROR_SKIPPARTIAL"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_MUSTACHELAMBDA",
            "name": "FLAG_MUSTACHELAMBDA",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_MUSTACHELAMBDA"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_NOHBHELPERS",
            "name": "FLAG_NOHBHELPERS",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_NOHBHELPERS"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_MUSTACHESECTION",
            "name": "FLAG_MUSTACHESECTION",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_MUSTACHESECTION"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_RENDER_DEBUG",
            "name": "FLAG_RENDER_DEBUG",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_RENDER_DEBUG"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_BESTPERFORMANCE",
            "name": "FLAG_BESTPERFORMANCE",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_BESTPERFORMANCE"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_JS",
            "name": "FLAG_JS",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_JS"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_INSTANCE",
            "name": "FLAG_INSTANCE",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_INSTANCE"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_MUSTACHE",
            "name": "FLAG_MUSTACHE",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_MUSTACHE"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_HANDLEBARS",
            "name": "FLAG_HANDLEBARS",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_HANDLEBARS"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_HANDLEBARSJS",
            "name": "FLAG_HANDLEBARSJS",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_HANDLEBARSJS"
        },                {
            "fqsen": "\\LightnCandy\\Flags\u003A\u003AFLAG_HANDLEBARSJS_FULL",
            "name": "FLAG_HANDLEBARSJS_FULL",
            "summary": "",
            "url": "classes/LightnCandy-Flags.html#constant_FLAG_HANDLEBARSJS_FULL"
        },                {
            "fqsen": "\\LightnCandy\\LightnCandy",
            "name": "LightnCandy",
            "summary": "LightnCandy\u0020major\u0020static\u0020class",
            "url": "classes/LightnCandy-LightnCandy.html"
        },                {
            "fqsen": "\\LightnCandy\\LightnCandy\u003A\u003Acompile\u0028\u0029",
            "name": "compile",
            "summary": "Compile\u0020handlebars\u0020template\u0020into\u0020PHP\u0020code.",
            "url": "classes/LightnCandy-LightnCandy.html#method_compile"
        },                {
            "fqsen": "\\LightnCandy\\LightnCandy\u003A\u003AcompilePartial\u0028\u0029",
            "name": "compilePartial",
            "summary": "Compile\u0020handlebars\u0020partial\u0020into\u0020PHP\u0020function\u0020code.",
            "url": "classes/LightnCandy-LightnCandy.html#method_compilePartial"
        },                {
            "fqsen": "\\LightnCandy\\LightnCandy\u003A\u003AhandleError\u0028\u0029",
            "name": "handleError",
            "summary": "Handle\u0020exists\u0020error\u0020and\u0020return\u0020error\u0020status.",
            "url": "classes/LightnCandy-LightnCandy.html#method_handleError"
        },                {
            "fqsen": "\\LightnCandy\\LightnCandy\u003A\u003AgetContext\u0028\u0029",
            "name": "getContext",
            "summary": "Get\u0020last\u0020compiler\u0020context.",
            "url": "classes/LightnCandy-LightnCandy.html#method_getContext"
        },                {
            "fqsen": "\\LightnCandy\\LightnCandy\u003A\u003Aprepare\u0028\u0029",
            "name": "prepare",
            "summary": "Get\u0020a\u0020working\u0020render\u0020function\u0020by\u0020a\u0020string\u0020of\u0020PHP\u0020code.\u0020This\u0020method\u0020may\u0020requires\u0020php\u0020setting\u0020allow_url_include\u003D1\u0020and\u0020allow_url_fopen\u003D1\u0020,\u0020or\u0020access\u0020right\u0020to\u0020tmp\u0020file\u0020system.",
            "url": "classes/LightnCandy-LightnCandy.html#method_prepare"
        },                {
            "fqsen": "\\LightnCandy\\LightnCandy\u003A\u003A\u0024lastContext",
            "name": "lastContext",
            "summary": "",
            "url": "classes/LightnCandy-LightnCandy.html#property_lastContext"
        },                {
            "fqsen": "\\LightnCandy\\LightnCandy\u003A\u003A\u0024lastParsed",
            "name": "lastParsed",
            "summary": "",
            "url": "classes/LightnCandy-LightnCandy.html#property_lastParsed"
        },                {
            "fqsen": "\\LightnCandy\\Parser",
            "name": "Parser",
            "summary": "LightnCandy\u0020Parser",
            "url": "classes/LightnCandy-Parser.html"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003AgetPartialBlock\u0028\u0029",
            "name": "getPartialBlock",
            "summary": "Get\u0020partial\u0020block\u0020id\u0020and\u0020fix\u0020the\u0020variable\u0020list",
            "url": "classes/LightnCandy-Parser.html#method_getPartialBlock"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003AgetBlockParams\u0028\u0029",
            "name": "getBlockParams",
            "summary": "Get\u0020block\u0020params\u0020and\u0020fix\u0020the\u0020variable\u0020list",
            "url": "classes/LightnCandy-Parser.html#method_getBlockParams"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003AgetLiteral\u0028\u0029",
            "name": "getLiteral",
            "summary": "Return\u0020array\u0020presentation\u0020for\u0020a\u0020literal",
            "url": "classes/LightnCandy-Parser.html#method_getLiteral"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003AgetExpression\u0028\u0029",
            "name": "getExpression",
            "summary": "Return\u0020array\u0020presentation\u0020for\u0020an\u0020expression",
            "url": "classes/LightnCandy-Parser.html#method_getExpression"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parse\u0020the\u0020token\u0020and\u0020return\u0020parsed\u0020result.",
            "url": "classes/LightnCandy-Parser.html#method_parse"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003AgetPartialName\u0028\u0029",
            "name": "getPartialName",
            "summary": "Get\u0020partial\u0020name\u0020from\u0020\u0022foo\u0022\u0020or\u0020\u005Bfoo\u005D\u0020or\u0020\\\u0027foo\\\u0027",
            "url": "classes/LightnCandy-Parser.html#method_getPartialName"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003Asubexpression\u0028\u0029",
            "name": "subexpression",
            "summary": "Parse\u0020a\u0020subexpression\u0020then\u0020return\u0020parsed\u0020result.",
            "url": "classes/LightnCandy-Parser.html#method_subexpression"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003AisSubExp\u0028\u0029",
            "name": "isSubExp",
            "summary": "Check\u0020a\u0020parsed\u0020result\u0020is\u0020a\u0020subexpression\u0020or\u0020not",
            "url": "classes/LightnCandy-Parser.html#method_isSubExp"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003AadvancedVariable\u0028\u0029",
            "name": "advancedVariable",
            "summary": "Analyze\u0020parsed\u0020token\u0020for\u0020advanved\u0020variables.",
            "url": "classes/LightnCandy-Parser.html#method_advancedVariable"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003AdetectQuote\u0028\u0029",
            "name": "detectQuote",
            "summary": "Detect\u0020quote\u0020charactors",
            "url": "classes/LightnCandy-Parser.html#method_detectQuote"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003Aanalyze\u0028\u0029",
            "name": "analyze",
            "summary": "Analyze\u0020a\u0020token\u0020string\u0020and\u0020return\u0020parsed\u0020result.",
            "url": "classes/LightnCandy-Parser.html#method_analyze"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003ABLOCKPARAM",
            "name": "BLOCKPARAM",
            "summary": "",
            "url": "classes/LightnCandy-Parser.html#constant_BLOCKPARAM"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003APARTIALBLOCK",
            "name": "PARTIALBLOCK",
            "summary": "",
            "url": "classes/LightnCandy-Parser.html#constant_PARTIALBLOCK"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003ALITERAL",
            "name": "LITERAL",
            "summary": "",
            "url": "classes/LightnCandy-Parser.html#constant_LITERAL"
        },                {
            "fqsen": "\\LightnCandy\\Parser\u003A\u003ASUBEXP",
            "name": "SUBEXP",
            "summary": "",
            "url": "classes/LightnCandy-Parser.html#constant_SUBEXP"
        },                {
            "fqsen": "\\LightnCandy\\Partial",
            "name": "Partial",
            "summary": "LightnCandy\u0020Partial\u0020handler",
            "url": "classes/LightnCandy-Partial.html"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003AhandleDynamic\u0028\u0029",
            "name": "handleDynamic",
            "summary": "Include\u0020all\u0020partials\u0020when\u0020using\u0020dynamic\u0020partials",
            "url": "classes/LightnCandy-Partial.html#method_handleDynamic"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020partial\u0020file\u0020content\u0020as\u0020string\u0020and\u0020store\u0020in\u0020context",
            "url": "classes/LightnCandy-Partial.html#method_read"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003AprePartial\u0028\u0029",
            "name": "prePartial",
            "summary": "preprocess\u0020partial\u0020template\u0020before\u0020it\u0020be\u0020stored\u0020into\u0020context",
            "url": "classes/LightnCandy-Partial.html#method_prePartial"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "resolve\u0020partial,\u0020return\u0020the\u0020partial\u0020content",
            "url": "classes/LightnCandy-Partial.html#method_resolve"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003Aresolver\u0028\u0029",
            "name": "resolver",
            "summary": "use\u0020partialresolver\u0020to\u0020resolve\u0020partial,\u0020return\u0020the\u0020partial\u0020content",
            "url": "classes/LightnCandy-Partial.html#method_resolver"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003AcompileStatic\u0028\u0029",
            "name": "compileStatic",
            "summary": "compile\u0020a\u0020partial\u0020to\u0020static\u0020embed\u0020PHP\u0020code",
            "url": "classes/LightnCandy-Partial.html#method_compileStatic"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003AcompileDynamic\u0028\u0029",
            "name": "compileDynamic",
            "summary": "compile\u0020partial\u0020as\u0020closure,\u0020stored\u0020in\u0020context",
            "url": "classes/LightnCandy-Partial.html#method_compileDynamic"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003Acompile\u0028\u0029",
            "name": "compile",
            "summary": "compile\u0020a\u0020template\u0020into\u0020a\u0020closure\u0020function",
            "url": "classes/LightnCandy-Partial.html#method_compile"
        },                {
            "fqsen": "\\LightnCandy\\Partial\u003A\u003A\u0024TMP_JS_FUNCTION_STR",
            "name": "TMP_JS_FUNCTION_STR",
            "summary": "",
            "url": "classes/LightnCandy-Partial.html#property_TMP_JS_FUNCTION_STR"
        },                {
            "fqsen": "\\LightnCandy\\StringObject",
            "name": "StringObject",
            "summary": "LightnCandy\u0020class\u0020for\u0020Object\u0020property\u0020access\u0020on\u0020a\u0020string.",
            "url": "classes/LightnCandy-StringObject.html"
        },                {
            "fqsen": "\\LightnCandy\\StringObject\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/LightnCandy-StringObject.html#method___construct"
        },                {
            "fqsen": "\\LightnCandy\\StringObject\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/LightnCandy-StringObject.html#method___toString"
        },                {
            "fqsen": "\\LightnCandy\\StringObject\u003A\u003A\u0024string",
            "name": "string",
            "summary": "",
            "url": "classes/LightnCandy-StringObject.html#property_string"
        },                {
            "fqsen": "\\LightnCandy\\Runtime",
            "name": "Runtime",
            "summary": "LightnCandy\u0020class\u0020for\u0020compiled\u0020PHP\u0020runtime.",
            "url": "classes/LightnCandy-Runtime.html"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Adebug\u0028\u0029",
            "name": "debug",
            "summary": "Output\u0020debug\u0020info.",
            "url": "classes/LightnCandy-Runtime.html#method_debug"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Aerr\u0028\u0029",
            "name": "err",
            "summary": "Handle\u0020error\u0020by\u0020error_log\u0020or\u0020throw\u0020exception.",
            "url": "classes/LightnCandy-Runtime.html#method_err"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Amiss\u0028\u0029",
            "name": "miss",
            "summary": "Handle\u0020missing\u0020data\u0020error.",
            "url": "classes/LightnCandy-Runtime.html#method_miss"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Alo\u0028\u0029",
            "name": "lo",
            "summary": "For\u0020\u007B\u007Blog\u007D\u007D\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_lo"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Av\u0028\u0029",
            "name": "v",
            "summary": "Resursive\u0020lookup\u0020variable\u0020and\u0020helpers.\u0020This\u0020is\u0020slow\u0020and\u0020will\u0020only\u0020be\u0020used\u0020for\u0020instance\u0020property\u0020or\u0020method\u0020detection\u0020or\u0020lambdas.",
            "url": "classes/LightnCandy-Runtime.html#method_v"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Aifvar\u0028\u0029",
            "name": "ifvar",
            "summary": "For\u0020\u007B\u007B\u0023if\u007D\u007D\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_ifvar"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Aisec\u0028\u0029",
            "name": "isec",
            "summary": "For\u0020\u007B\u007B\u005Evar\u007D\u007D\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_isec"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Aenc\u0028\u0029",
            "name": "enc",
            "summary": "For\u0020\u007B\u007Bvar\u007D\u007D\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_enc"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Aencq\u0028\u0029",
            "name": "encq",
            "summary": "For\u0020\u007B\u007Bvar\u007D\u007D\u0020,\u0020do\u0020html\u0020encode\u0020just\u0020like\u0020handlebars.js\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_encq"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Asec\u0028\u0029",
            "name": "sec",
            "summary": "For\u0020\u007B\u007B\u0023var\u007D\u007D\u0020or\u0020\u007B\u007B\u0023each\u007D\u007D\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_sec"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Awi\u0028\u0029",
            "name": "wi",
            "summary": "For\u0020\u007B\u007B\u0023with\u007D\u007D\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_wi"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Am\u0028\u0029",
            "name": "m",
            "summary": "Get\u0020merged\u0020context.",
            "url": "classes/LightnCandy-Runtime.html#method_m"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Ap\u0028\u0029",
            "name": "p",
            "summary": "For\u0020\u007B\u007B\u003E\u0020partial\u007D\u007D\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_p"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Ain\u0028\u0029",
            "name": "in",
            "summary": "For\u0020\u007B\u007B\u0023\u002A\u0020inlinepartial\u007D\u007D\u0020.",
            "url": "classes/LightnCandy-Runtime.html#method_in"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Ahbch\u0028\u0029",
            "name": "hbch",
            "summary": "",
            "url": "classes/LightnCandy-Runtime.html#method_hbch"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Ahbbch\u0028\u0029",
            "name": "hbbch",
            "summary": "For\u0020block\u0020custom\u0020helpers.",
            "url": "classes/LightnCandy-Runtime.html#method_hbbch"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003Aexch\u0028\u0029",
            "name": "exch",
            "summary": "Execute\u0020custom\u0020helper\u0020with\u0020prepared\u0020options",
            "url": "classes/LightnCandy-Runtime.html#method_exch"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003ADEBUG_ERROR_LOG",
            "name": "DEBUG_ERROR_LOG",
            "summary": "",
            "url": "classes/LightnCandy-Runtime.html#constant_DEBUG_ERROR_LOG"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003ADEBUG_ERROR_EXCEPTION",
            "name": "DEBUG_ERROR_EXCEPTION",
            "summary": "",
            "url": "classes/LightnCandy-Runtime.html#constant_DEBUG_ERROR_EXCEPTION"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003ADEBUG_TAGS",
            "name": "DEBUG_TAGS",
            "summary": "",
            "url": "classes/LightnCandy-Runtime.html#constant_DEBUG_TAGS"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003ADEBUG_TAGS_ANSI",
            "name": "DEBUG_TAGS_ANSI",
            "summary": "",
            "url": "classes/LightnCandy-Runtime.html#constant_DEBUG_TAGS_ANSI"
        },                {
            "fqsen": "\\LightnCandy\\Runtime\u003A\u003ADEBUG_TAGS_HTML",
            "name": "DEBUG_TAGS_HTML",
            "summary": "",
            "url": "classes/LightnCandy-Runtime.html#constant_DEBUG_TAGS_HTML"
        },                {
            "fqsen": "\\LightnCandy\\SafeString",
            "name": "SafeString",
            "summary": "LightnCandy\u0020SafeString\u0020class",
            "url": "classes/LightnCandy-SafeString.html"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/LightnCandy-SafeString.html#method___construct"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/LightnCandy-SafeString.html#method___toString"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003AstripExtendedComments\u0028\u0029",
            "name": "stripExtendedComments",
            "summary": "Strip\u0020extended\u0020comments\u0020\u007B\u007B\u0021\u002D\u002D\u0020....\u0020\u002D\u002D\u007D\u007D",
            "url": "classes/LightnCandy-SafeString.html#method_stripExtendedComments"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003AescapeTemplate\u0028\u0029",
            "name": "escapeTemplate",
            "summary": "Escape\u0020template",
            "url": "classes/LightnCandy-SafeString.html#method_escapeTemplate"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003AEXTENDED_COMMENT_SEARCH",
            "name": "EXTENDED_COMMENT_SEARCH",
            "summary": "",
            "url": "classes/LightnCandy-SafeString.html#constant_EXTENDED_COMMENT_SEARCH"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003AIS_SUBEXP_SEARCH",
            "name": "IS_SUBEXP_SEARCH",
            "summary": "",
            "url": "classes/LightnCandy-SafeString.html#constant_IS_SUBEXP_SEARCH"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003AIS_BLOCKPARAM_SEARCH",
            "name": "IS_BLOCKPARAM_SEARCH",
            "summary": "",
            "url": "classes/LightnCandy-SafeString.html#constant_IS_BLOCKPARAM_SEARCH"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003A\u0024string",
            "name": "string",
            "summary": "",
            "url": "classes/LightnCandy-SafeString.html#property_string"
        },                {
            "fqsen": "\\LightnCandy\\SafeString\u003A\u003A\u0024jsContext",
            "name": "jsContext",
            "summary": "",
            "url": "classes/LightnCandy-SafeString.html#property_jsContext"
        },                {
            "fqsen": "\\LightnCandy\\Token",
            "name": "Token",
            "summary": "LightnCandy\u0020Token\u0020handler",
            "url": "classes/LightnCandy-Token.html"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003AsetDelimiter\u0028\u0029",
            "name": "setDelimiter",
            "summary": "Setup\u0020delimiter\u0020by\u0020default\u0020or\u0020provided\u0020string",
            "url": "classes/LightnCandy-Token.html#method_setDelimiter"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "return\u0020token\u0020string",
            "url": "classes/LightnCandy-Token.html#method_toString"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003AVARNAME_SEARCH",
            "name": "VARNAME_SEARCH",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_VARNAME_SEARCH"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_LOTHER",
            "name": "POS_LOTHER",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_LOTHER"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_LSPACE",
            "name": "POS_LSPACE",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_LSPACE"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_BEGINTAG",
            "name": "POS_BEGINTAG",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_BEGINTAG"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_LSPACECTL",
            "name": "POS_LSPACECTL",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_LSPACECTL"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_BEGINRAW",
            "name": "POS_BEGINRAW",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_BEGINRAW"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_OP",
            "name": "POS_OP",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_OP"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_INNERTAG",
            "name": "POS_INNERTAG",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_INNERTAG"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_ENDRAW",
            "name": "POS_ENDRAW",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_ENDRAW"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_RSPACECTL",
            "name": "POS_RSPACECTL",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_RSPACECTL"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_ENDTAG",
            "name": "POS_ENDTAG",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_ENDTAG"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_RSPACE",
            "name": "POS_RSPACE",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_RSPACE"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_ROTHER",
            "name": "POS_ROTHER",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_ROTHER"
        },                {
            "fqsen": "\\LightnCandy\\Token\u003A\u003APOS_BACKFILL",
            "name": "POS_BACKFILL",
            "summary": "",
            "url": "classes/LightnCandy-Token.html#constant_POS_BACKFILL"
        },                {
            "fqsen": "\\LightnCandy\\Validator",
            "name": "Validator",
            "summary": "LightnCandy\u0020Validator",
            "url": "classes/LightnCandy-Validator.html"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Averify\u0028\u0029",
            "name": "verify",
            "summary": "Verify\u0020template",
            "url": "classes/LightnCandy-Validator.html#method_verify"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003ApushLeft\u0028\u0029",
            "name": "pushLeft",
            "summary": "push\u0020left\u0020string\u0020of\u0020current\u0020token\u0020and\u0020clear\u0020it",
            "url": "classes/LightnCandy-Validator.html#method_pushLeft"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003ApushPartial\u0028\u0029",
            "name": "pushPartial",
            "summary": "push\u0020a\u0020string\u0020into\u0020the\u0020partial\u0020stacks",
            "url": "classes/LightnCandy-Validator.html#method_pushPartial"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003ApushToken\u0028\u0029",
            "name": "pushToken",
            "summary": "push\u0020a\u0020token\u0020into\u0020the\u0020stack\u0020when\u0020it\u0020is\u0020not\u0020empty\u0020string",
            "url": "classes/LightnCandy-Validator.html#method_pushToken"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003ApushStack\u0028\u0029",
            "name": "pushStack",
            "summary": "push\u0020current\u0020token\u0020into\u0020the\u0020section\u0020stack",
            "url": "classes/LightnCandy-Validator.html#method_pushStack"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Adelimiter\u0028\u0029",
            "name": "delimiter",
            "summary": "Verify\u0020delimiters\u0020and\u0020operators",
            "url": "classes/LightnCandy-Validator.html#method_delimiter"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Aoperator\u0028\u0029",
            "name": "operator",
            "summary": "Verify\u0020operators",
            "url": "classes/LightnCandy-Validator.html#method_operator"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AinlinePartial\u0028\u0029",
            "name": "inlinePartial",
            "summary": "validate\u0020inline\u0020partial\u0020begin\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_inlinePartial"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003ApartialBlock\u0028\u0029",
            "name": "partialBlock",
            "summary": "validate\u0020partial\u0020block\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_partialBlock"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AdoElseChain\u0028\u0029",
            "name": "doElseChain",
            "summary": "handle\u0020else\u0020chain",
            "url": "classes/LightnCandy-Validator.html#method_doElseChain"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AblockBegin\u0028\u0029",
            "name": "blockBegin",
            "summary": "validate\u0020block\u0020begin\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_blockBegin"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Abuiltin\u0028\u0029",
            "name": "builtin",
            "summary": "validate\u0020builtin\u0020helpers",
            "url": "classes/LightnCandy-Validator.html#method_builtin"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Asection\u0028\u0029",
            "name": "section",
            "summary": "validate\u0020section\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_section"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Awith\u0028\u0029",
            "name": "with",
            "summary": "validate\u0020with\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_with"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Aunless\u0028\u0029",
            "name": "unless",
            "summary": "validate\u0020unless\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_unless"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AdoIf\u0028\u0029",
            "name": "doIf",
            "summary": "validate\u0020if\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_doIf"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AblockCustomHelper\u0028\u0029",
            "name": "blockCustomHelper",
            "summary": "validate\u0020block\u0020custom\u0020helper\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_blockCustomHelper"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AinvertedSection\u0028\u0029",
            "name": "invertedSection",
            "summary": "validate\u0020inverted\u0020section",
            "url": "classes/LightnCandy-Validator.html#method_invertedSection"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AblockEnd\u0028\u0029",
            "name": "blockEnd",
            "summary": "Return\u0020compiled\u0020PHP\u0020code\u0020for\u0020a\u0020handlebars\u0020block\u0020end\u0020token",
            "url": "classes/LightnCandy-Validator.html#method_blockEnd"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AisDelimiter\u0028\u0029",
            "name": "isDelimiter",
            "summary": "handle\u0020delimiter\u0020change",
            "url": "classes/LightnCandy-Validator.html#method_isDelimiter"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Arawblock\u0028\u0029",
            "name": "rawblock",
            "summary": "handle\u0020raw\u0020block",
            "url": "classes/LightnCandy-Validator.html#method_rawblock"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Acomment\u0028\u0029",
            "name": "comment",
            "summary": "handle\u0020comment",
            "url": "classes/LightnCandy-Validator.html#method_comment"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Atoken\u0028\u0029",
            "name": "token",
            "summary": "Collect\u0020handlebars\u0020usage\u0020information,\u0020detect\u0020template\u0020error.",
            "url": "classes/LightnCandy-Validator.html#method_token"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AdoElse\u0028\u0029",
            "name": "doElse",
            "summary": "Return\u00201\u0020or\u0020larger\u0020number\u0020when\u0020else\u0020token\u0020detected",
            "url": "classes/LightnCandy-Validator.html#method_doElse"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "Return\u0020true\u0020when\u0020this\u0020is\u0020\u007B\u007Blog\u0020...\u007D\u007D",
            "url": "classes/LightnCandy-Validator.html#method_log"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Alookup\u0028\u0029",
            "name": "lookup",
            "summary": "Return\u0020true\u0020when\u0020this\u0020is\u0020\u007B\u007Blookup\u0020...\u007D\u007D",
            "url": "classes/LightnCandy-Validator.html#method_lookup"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Ahelper\u0028\u0029",
            "name": "helper",
            "summary": "Return\u0020true\u0020when\u0020the\u0020name\u0020is\u0020listed\u0020in\u0020helper\u0020table",
            "url": "classes/LightnCandy-Validator.html#method_helper"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AresolveHelper\u0028\u0029",
            "name": "resolveHelper",
            "summary": "use\u0020helperresolver\u0020to\u0020resolve\u0020helper,\u0020return\u0020true\u0020when\u0020helper\u0020founded",
            "url": "classes/LightnCandy-Validator.html#method_resolveHelper"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003AisBlockHelper\u0028\u0029",
            "name": "isBlockHelper",
            "summary": "detect\u0020for\u0020block\u0020custom\u0020helper",
            "url": "classes/LightnCandy-Validator.html#method_isBlockHelper"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Ainline\u0028\u0029",
            "name": "inline",
            "summary": "validate\u0020inline\u0020partial",
            "url": "classes/LightnCandy-Validator.html#method_inline"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Apartial\u0028\u0029",
            "name": "partial",
            "summary": "validate\u0020partial",
            "url": "classes/LightnCandy-Validator.html#method_partial"
        },                {
            "fqsen": "\\LightnCandy\\Validator\u003A\u003Aspacing\u0028\u0029",
            "name": "spacing",
            "summary": "Modify\u0020\u0024token\u0020when\u0020spacing\u0020rules\u0020matched.",
            "url": "classes/LightnCandy-Validator.html#method_spacing"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\LightnCandy",
            "name": "LightnCandy",
            "summary": "",
            "url": "namespaces/lightncandy.html"
        }            ]
);
