<?php
require('src/lightncandy.php');
$template = <<<VAREND
Test {{testerr1}}} ....
Test {{{testerr2}} ....
Test {{{#testerr3}}} ....
Test {{{!testerr4}}} ....
Test {{{^testerr5}}} ....
Test {{{/testerr6}}} ....
This is {{win[ner.test1}} ....
That is {{win]ner.test2}} ....
That is {{wi[n]ner.test3}} ....
That is {{winner].[test4]}} ....
That is {{winner[.test5]}} ....
That is {{winner.[.test6]}} ....
That is {{winner.[#te.st7]}} ....
That is {{test8}} ....
That is {{test9]}} ....
That is {{testA[}} ....
That is {{[testB}} ....
That is {{]testC}} ....
That is {{[testD]}} ....
That is {{te]stE}} ....
That is {{tee[stF}} ....
That is {{te.e[stG}} ....
That is {{te.e]stH}} ....
That is {{te.e[st.endI}} ....
That is {{te.e]st.endJ}} ....
That is {{te.[est].endK}} ....
That is {{te.t[est].endL}} ....
That is {{te.t[est]o.endM}} ....
That is {{te.[est]o.endN}} ....
That is {{te.[e.st].endO}} ....
That is {{te.[e.s[t].endP}} ....
That is {{te.[e[s.t].endQ}} ....
That is {{~test}} ....
That is {{#if test~}}OK{{/if~}} ....
<ul>
{{#each item}}<li>{{name}}</li>
</ul>
VAREND
;
$php = LightnCandy::compile($template, Array('flags' => LightnCandy::FLAG_ERROR_LOG | LightnCandy::FLAG_STANDALONE | LightnCandy::FLAG_HANDLEBARSJS));

echo "Template is:\n$template\n\n";
echo "Rendered PHP code is:\n$php\n\n";
echo 'LightnCandy Context:';
print_r(LightnCandy::getContext());

?>
