<?php
/**
 * Generated by build/gen_test on 2014-02-26 at 05:34:15.
 */
require_once('src/lightncandy.php');

class LCRunTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers LCRun::ifvar
     */
    public function testOn_ifvar() {
        $method = new ReflectionMethod('LCRun', 'ifvar');
        $this->assertEquals(false, $method->invoke(null, 'a', Array(), Array()));
        $this->assertEquals(false, $method->invoke(null, 'a', Array(), Array('a' => null)));
        $this->assertEquals(false, $method->invoke(null, 'a', Array(), Array('a' => 0)));
        $this->assertEquals(false, $method->invoke(null, 'a', Array(), Array('a' => false)));
        $this->assertEquals(true, $method->invoke(null, 'a', Array(), Array('a' => true)));
        $this->assertEquals(true, $method->invoke(null, 'a', Array(), Array('a' => 1)));
    }
}
?>