<?php
/**
 * Generated by build/gen_test on 2014-02-26 at 05:34:15.
 */
include('src/lightncandy.inc');
class LightnCandyTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers LightnCandy::_vs
     */
    public function testOn__vs() {
        $method = new ReflectionMethod('LightnCandy', '_vs');
        $method->setAccessible(true);
        $this->assertEquals(Array('.'), $method->invoke(null, '.'));
    }
}

class LCRunTest extends PHPUnit_Framework_TestCase
{
}

?>