<?php
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use LightnCandy\Runtime;

require_once(__DIR__ . '/test_util.php');

class PartialTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers LightnCandy\Partial::prePartial
     */
    public function testOn_prePartial() {
        $method = new \ReflectionMethod('LightnCandy\Partial', 'prePartial');
        $method->setAccessible(true);
        $this->assertEquals('hey', $method->invokeArgs(null, array_by_ref(array(
            'hey', 'haha', Array('prepartial' => false)
        ))));
        $this->assertEquals('haha-hoho', $method->invokeArgs(null, array_by_ref(array(
            'hoho', 'haha', Array('prepartial' => function ($tmpl, $name) {return "$name-$tmpl";})
        ))));
    }
}
?>