<?php
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use LightnCandy\Runtime;

class StringTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers LightnCandy\String::stripExtendedComments
     */
    public function testOn_stripExtendedComments() {
        $method = new \ReflectionMethod('LightnCandy\String', 'stripExtendedComments');
        $this->assertEquals('abc', $method->invokeArgs(null,array(
            'abc'
)        ));
        $this->assertEquals('abc{{!}}cde', $method->invokeArgs(null,array(
            'abc{{!}}cde'
)        ));
        $this->assertEquals('abc{{! }}cde', $method->invokeArgs(null,array(
            'abc{{!----}}cde'
)        ));
    }
    /**
     * @covers LightnCandy\String::escapeTemplate
     */
    public function testOn_escapeTemplate() {
        $method = new \ReflectionMethod('LightnCandy\String', 'escapeTemplate');
        $this->assertEquals('abc', $method->invokeArgs(null,array(
            'abc'
)        ));
        $this->assertEquals('a\\\\bc', $method->invokeArgs(null,array(
            'a\bc'
)        ));
        $this->assertEquals('a\\\'bc', $method->invokeArgs(null,array(
            'a\'bc'
)        ));
    }
}
?>