<?php
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use LightnCandy\Runtime;

class TokenTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers LightnCandy\Token::toString
     */
    public function testOn_toString() {
        $method = new \ReflectionMethod('LightnCandy\Token', 'toString');
        $this->assertEquals('c', $method->invokeArgs(null,array(
            array(0, 'a', 'b', 'c', 'd', 'e')
)        ));
    }
}
?>